{{- if .Values.reloader.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seatunnel.reloader.serviceAccountName" . }}
  {{- with .Values.reloader.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.reloader.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
