apiVersion: v1
kind: Service
metadata:
  name: {{ include "seatunnel.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "seatunnel.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5801
      name: seatunnel
